Ext.define('Wei.model.account.User', {
    extend: 'Wei.model.Base',

    fields: [
        { type: 'int', name: 'id', persist: true },
        { type: 'string', name: 'loginname', persist: false },
        { type: 'string', name: 'password', persist: false },
        { type: 'string', name: 'passwordsalt', persist: false },
        { type: 'string', name: 'firstname', persist: true },
        { type: 'string', name: 'lastname', persist: true },
        { type: 'string', name: 'phone', persist: true },
        { type: 'string', name: 'qq', persist: true },
        { type: 'string', name: 'email', persist: true },
        { type: 'string', name: 'channel', persist: true },
        { type: 'date', name: 'createtime', persist: false },
        { type: 'date', name: 'lastlogintime', persist: false },
        { type: 'string', name: 'lastloginip', persist: false },
        { type: 'date', name: 'lastactivitytime', persist: false },
        { type: 'int', name: 'status', persist: false },
        { type: 'int', name: 'isadmin', persist: false },
        { type: 'string', name: 'loginticket', persist: false },
        { type: 'int', name: 'loginscount', persist: false },
        { type: 'int', name: 'subscribe', persist: false },
        { type: 'string', name: 'openid', persist: false },
        { type: 'string', name: 'nickname', persist: true },
        { type: 'int', name: 'sex', persist: false },
        { type: 'date', name: 'birthdate', persist: true },
        { type: 'string', name: 'language', persist: true },
        { type: 'string', name: 'city', persist: true },
        { type: 'string', name: 'province', persist: true },
        { type: 'string', name: 'country', persist: true },
        { type: 'string', name: 'headimgurl', persist: true },
        { type: 'int', name: 'subscribe_time', persist: false },
        { type: 'string', name: 'unionid', persist: false },
        { type: 'string', name: 'remark', persist: true },
        { type: 'int', name: 'groupid', persist: true },
        { type: 'string', name: 'tagids', persist: true },
        { type: 'string', name: 'subscribe_scene', persist: false },
        { type: 'int', name: 'qr_scene', persist: false },
        { type: 'string', name: 'qr_scene_str', persist: false },
        { type: 'string', name: 'address', persist: true },
        { type: 'bool', name: 'married', persist: true },
        { type: 'string', name: 'identitycard', persist: true },
        { type: 'string', name: 'education', persist: true }
    ]
});
